[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
db_host = odoo-db
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$qDUGwHhvbS0lRAhhbC0lhA$Jy68Mn3Shs52F3k5Z.yLdl3GC7hsr0eUDQx6XRjG5.MMXHqdvapgjsQAj8Ui0A0fKQW7/LcYmxtpYbSr.07aQw
http_port = 8069
logfile = /var/log/odoo/odoo.log
log_level = info

