[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
db_host = odoo-db
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = multipower2026
http_port = 8069
logfile = /var/log/odoo/odoo.log
log_level = info

